spring:
  datasource:
    url: jdbc:ucanaccess://C:/Users/lalup/OneDrive/Desktop/netzwerk/net2.accdb
#    "C:\Users\lalup\OneDrive\Desktop\netzwerk\net2.accdb"
    driver-class-name: net.ucanaccess.jdbc.UcanaccessDriver
    username: ""
    password: ""
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:

        dialect: org.hibernate.dialect.SQLServerDialect      #HSQL - HyperSQL / Hibernate

#  datasource:
#    url: jdbc:mysql://localhost:3306/netswerk
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: "root"
#    password: "root"
#  jpa:
#    hibernate:
#      ddl-auto: update  # or update, create, etc.
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect  # Use MySQL8Dialect for MySQL 8.x or MySQLDialect for older versions
